name: Build and Release

on:
  push:
    branches:
      - main  # 监听 main 分支，改成你需要的分支

env:
  FLUTTER_VERSION: '3.29.3'

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Package Windows Files
        run: |
          mkdir out
          Compress-Archive -Path build/windows/runner/Release/* -DestinationPath out/HiddifyWithPanels-windows.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: out/HiddifyWithPanels-windows.zip
          retention-days: 7

  build_apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/flutter-apk/*.apk
          retention-days: 7

  release:
    needs: [build_windows, build_apk]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: ./release_files

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "HiddifyWithPanels Release v${{ github.run_number }}"
          draft: false
          prerelease: false
          files: release_files/HiddifyWithPanels-windows.zip, release_files/*.apk
